export {}
// generated by typed-config.js
declare module "atom" {
  interface ConfigValues {
    "typescript-pulsar.unusedAsInfo": boolean
    "typescript-pulsar.checkAllFilesOnSave": boolean
    "typescript-pulsar.autocompletionSuggestionPriority": number
    "typescript-pulsar.autocompletionInclusionPriority": number
    "typescript-pulsar.autocompletionExcludeLowerPriority": boolean
    "typescript-pulsar.autocompletionUseFuzzyFilter": boolean
    "typescript-pulsar.autocompletionStrictFilterIgnoreCase": boolean
    "typescript-pulsar.autocompletionStrictFilterLongestMatchFirst": boolean
    "typescript-pulsar.locale": string
    "typescript-pulsar.preferBuiltinTooltips": boolean
    "typescript-pulsar.preferBuiltinSigHelp": boolean
    "typescript-pulsar.preferBuiltinBusySignal": boolean
    "typescript-pulsar.preferBuiltinOccurrenceHighlight": boolean
    "typescript-pulsar.disableAtomIdeDefinitions": boolean
    "typescript-pulsar.buildStatusTimeout": number
    "typescript-pulsar.getErrDebounceTimeout": number
    "typescript-pulsar.occurrenceHighlightDebounceTimeout": number
    "typescript-pulsar.showSemanticView": boolean
    "typescript-pulsar.tooltipDelay": number
    "typescript-pulsar.tooltipPosition": "top" | "bottom"
    "typescript-pulsar.sigHelpPosition": "top" | "bottom"
    "typescript-pulsar.sigHelpDisplayOnChange": boolean
    "typescript-pulsar.autocompleteParens": boolean
    "typescript-pulsar.includeCompletionsForModuleExports": boolean
    "typescript-pulsar.quotePreference": "auto" | "double" | "single"
    "typescript-pulsar.importModuleSpecifierEnding": "auto" | "minimal" | "index" | "js"
    "typescript-pulsar.importModuleSpecifierPreference":
      | "auto"
      | "relative"
      | "non-relative"
      | "shortest"
      | "project-relative"
    "typescript-pulsar.typescriptSource": "auto" | "bundled" | "tsdkPath" | "local"
    "typescript-pulsar.tsdkPath": string
    "typescript-pulsar.ignoredDiagnosticCodes": string[]
    "typescript-pulsar.ignoreUnusedSuggestionDiagnostics": boolean
    "typescript-pulsar.ignoreNonSuggestionSuggestionDiagnostics": boolean
    "typescript-pulsar.ignoredSuggestionDiagnostics": string[]
    "typescript-pulsar.suppressAllDiagnostics": boolean
    "typescript-pulsar.tsFileExtensions": string[]
    "typescript-pulsar.jsFileExtensions": string[]
    "typescript-pulsar.extensionsFromGrammars": boolean
    "typescript-pulsar.tsSyntaxScopes": string[]
    "typescript-pulsar.jsSyntaxScopes": string[]
    "typescript-pulsar.allowJS": boolean
    "typescript-pulsar.tsserverInstancePerTsconfig": boolean
    "typescript-pulsar.longLineLength": number
    "typescript-pulsar.largeFileLineCount": number
    "typescript-pulsar.largeFileNoFollowCursor": boolean
    "typescript-pulsar": {
      unusedAsInfo: boolean
      checkAllFilesOnSave: boolean
      autocompletionSuggestionPriority: number
      autocompletionInclusionPriority: number
      autocompletionExcludeLowerPriority: boolean
      autocompletionUseFuzzyFilter: boolean
      autocompletionStrictFilterIgnoreCase: boolean
      autocompletionStrictFilterLongestMatchFirst: boolean
      locale: string
      preferBuiltinTooltips: boolean
      preferBuiltinSigHelp: boolean
      preferBuiltinBusySignal: boolean
      preferBuiltinOccurrenceHighlight: boolean
      disableAtomIdeDefinitions: boolean
      buildStatusTimeout: number
      getErrDebounceTimeout: number
      occurrenceHighlightDebounceTimeout: number
      showSemanticView: boolean
      tooltipDelay: number
      tooltipPosition: "top" | "bottom"
      sigHelpPosition: "top" | "bottom"
      sigHelpDisplayOnChange: boolean
      autocompleteParens: boolean
      includeCompletionsForModuleExports: boolean
      quotePreference: "auto" | "double" | "single"
      importModuleSpecifierEnding: "auto" | "minimal" | "index" | "js"
      importModuleSpecifierPreference:
        | "auto"
        | "relative"
        | "non-relative"
        | "shortest"
        | "project-relative"
      typescriptSource: "auto" | "bundled" | "tsdkPath" | "local"
      tsdkPath: string
      ignoredDiagnosticCodes: string[]
      ignoreUnusedSuggestionDiagnostics: boolean
      ignoreNonSuggestionSuggestionDiagnostics: boolean
      ignoredSuggestionDiagnostics: string[]
      suppressAllDiagnostics: boolean
      tsFileExtensions: string[]
      jsFileExtensions: string[]
      extensionsFromGrammars: boolean
      tsSyntaxScopes: string[]
      jsSyntaxScopes: string[]
      allowJS: boolean
      tsserverInstancePerTsconfig: boolean
      longLineLength: number
      largeFileLineCount: number
      largeFileNoFollowCursor: boolean
    }
  }
}
