# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pulsar-edit/action-pulsar-dependency@v3.3
      - name: Pulsar version
        run: pulsar -v
      - name: PPM version
        run: ppm -v
      - name: Install dependencies
        run: ppm ci
      - name: Build required artifacts
        run: npm run build
      - name: Run tests
        uses: coactions/setup-xvfb@v1.0.1
        with:
          run: pulsar --no-sandbox --test spec
      - name: Run static checks
        shell: bash
        run: npm test
      - name: Check for changed files
        shell: bash
        run: git diff --quiet -- dist/
      - name: Check for new files
        shell: bash
        run: |
          untracked="$(git ls-files --others --exclude-standard)" && echo "$untracked" && test -z "$untracked"
